# Default values for naiserator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  defaultRoles: "admin,naisdeveloper"
  defaultRolebindingPrefix: "teammembers"
  updateInterval: "15m"
  iamSecret: ""

image:
  repository: "europe-north1-docker.pkg.dev/nais-io/nais/images/rbac-sync"
  pullPolicy: "IfNotPresent"
  tag: "main"

podSecurityContext:
  fsGroup: 65532
  runAsNonRoot: true
  supplementalGroups:
    - 65532
  seccompProfile:
    type: RuntimeDefault

  # fsGroup: 2000

replicas: 1

containerSecurityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
